export const SKILL_ICON_FILE: Record<string, string> = {
  TypeScript: "typescript.svg",
  Python: "python.svg",
  "C#": "csharp.svg",
  "C++": "cplusplus.svg",
  JavaScript: "javascript.svg",
  HTML: "html5.svg",
  CSS: "css.svg",
  Go: "go.svg",
  "Next.js": "nextdotjs.svg",
  React: "react.svg",
  Unity: "unity.svg",
  Godot: "godotengine.svg",
  "Node.js": "nodedotjs.svg",
  "Express.js": "express.svg",
  FastAPI: "fastapi.svg",
  Gin: "wb.svg",
  PostgreSQL: "postgresql.svg",
  MongoDB: "mongodb.svg",
  Supabase: "supabase.svg",
  "Cloudflare R2": "cloudflare.svg",
  Docker: "docker.svg",
};
